app:
  logFile: log/gin.log
  httpPort: 8080
  webSocketPort: 8089
  rpcPort: 9001
  httpUrl: 127.0.0.1:8080
  webSocketUrl:  127.0.0.1:8089
redis:
  addr: "47.93.83.136:6379"
  password: "123456"
  DB: 2
  poolSize: 30
  minIdleConns: 30